FORMAT: 1A
HOST: https://www.ascribe.io/***REMOVED***/api

# ***REMOVED***-sylvain

Polls is a simple API allowing consumers to view polls and vote in them.

## Designs Collection [/designs]

### List All Designs [GET]

Not yet implemented

+ Response 200 (application/json)

### Create a New Design [POST]

You may create your own design ...

+ Request (application/json)

    + Attributes
        + stereo_lithographic_id (string, required) - an identifier for the STL file. must be unique.
        + stereo_lithographic_url (string, required) - the PUBLIC url pointing to the STL file (optional)

    + Header
        
            Authorization: <your_api_token>
    
    + Body
        
            {
                "stereo_lithographic_id": "abc-123-xyz",
                "stereo_lithographic_url": "https://3dmodel.stl"
            }

+ Response 201 (application/json)


### Search a Design [GET /designs/search]

You may search your own design ...

+ Request (application/json)

    + Attributes
        + stereo_lithographic_id (string, required) - an identifier for the STL file. must be unique.

    + Header
        
            Authorization: <your_api_token>
    
    + Body
        
            {
                "stereo_lithographic_id": "abc-123-xyz",
            }

+ Response 200 (application/json)


### Retrieve a Design [GET /designs/{stl_id}]

Not yet implemented

+ Response 200 (application/json)


### Render a Design [GET /designs/{stl_id}/render]

Renders an STL file into images. The input is an STL file.
The output is three or more images, rendered from various angles.

+ Response 200 (application/json)

